#!/bin/bash
#-------------------------------------------------------------------------------
# Account information
#SBATCH --account=phd              # basic (default), staff, phd, faculty
#-------------------------------------------------------------------------------
# Resources requested
#SBATCH --partition=standard      # standard (default), long, gpu, mpi, highmem
#SBATCH --cpus-per-task=1          # number of CPUs requested (for parallel tasks)
#SBATCH --mem=32G           # requested memory
#SBATCH --time=0-010:00:00          # wall clock limit (d-hh:mm:ss)
#---------------------------------------------------------------------------------
# Job specific name (helps organize and track progress of jobs)

# SBATCH --job-name=Call_R  # user-defined job name

#---------------------------------------------------------------------------------
# Print some useful variables

echo "Job ID: $SLURM_JOB_ID"
echo "Job User: $SLURM_JOB_USER"
echo "Num Cores: $SLURM_JOB_CPUS_PER_NODE"

#-------------------------------------------------------------------------------

# Load the module with the desired version of R
module load R/3.6/3.6.2

# Passing Array ID 
# run Rscript (output will be written to slurm-<jobid>.out)
srun Rscript  ~/developers/code/link_map_tracts.R